#include<iostream.h>
#include<conio.h>
void main()
{
clrscr();
outtextxy(31,2," \\ \n   \\ \n     \\\n       \\ \n         \\\n           \\\n             \\\n               \\\n                 \\\n 		   \\");
outtextxy(50,2, "                     /\n                   /\n                 /\n               /\n             / \n           /\n         /\n       /\n     /\n   /");
outtextxy(31,2,"
outtextxy(31,6,"
outtextxy(40,10,"}
